export const logs = [
  { type: "pending", id: "0" },
  { type: "pending", id: "2", parentId: "0" },
  { type: "pending", id: "3", parentId: "0" },
  { type: "pending", id: "4", parentId: "3" },
  { type: "pending", id: "5", parentId: "4" },
  { type: "pending", id: "6", parentId: "4" },
  { type: "pending", id: "7", parentId: "0" },
  { type: "pending", id: "8", parentId: "0" },
  { type: "pending", id: "9", parentId: "0" },
  { type: "pending", id: "10", parentId: "0" },
  { type: "pending", id: "11", parentId: "0" },
  { type: "pending", id: "12", parentId: "0" },
  { type: "pending", id: "13", parentId: "0" },
  { type: "pending", id: "14", parentId: "0" },
  { type: "pending", id: "15", parentId: "0" },
  { type: "pending", id: "16", parentId: "0" },
  {
    type: "finalized",
    id: "12",
    result: { exists: true, value: { ok: true, value: "6 is done" } },
  },
  {
    type: "finalized",
    id: "14",
    result: { exists: true, value: { ok: true, value: "8 is done" } },
  },
  {
    type: "finalized",
    id: "8",
    result: { exists: true, value: { ok: true, value: "2 is done" } },
  },
  {
    type: "finalized",
    id: "10",
    result: { exists: true, value: { ok: true, value: "4 is done" } },
  },
  { type: "finalized", id: "7", result: { exists: false } },
  { type: "finalized", id: "9", result: { exists: false } },
  {
    type: "finalized",
    id: "13",
    result: { exists: true, value: { ok: true, value: "7 is done" } },
  },
  { type: "finalized", id: "11", result: { exists: false } },
  {
    type: "finalized",
    id: "16",
    result: { exists: true, value: { ok: true, value: "10 is done" } },
  },
  { type: "finalized", id: "15", result: { exists: false } },
];
